baseURL = 'https://olessia.fr'
category = "categories"
tag = "tags"

defaultContentLanguage = 'fr'
defaultContentLanguageInSubdir = true

[languages]

  [languages.ua]

    contentDir = 'content/ua'
    disabled = false
    languageCode = 'uk-UA'
    languageDirection = 'ltr'
    languageName = 'українська'
    title = 'Олеся, Ваш психолог'
    weight = 2

    [languages.ua.params]
      subtitle = 'Навчись будувати якісне життя.'

  [languages.fr]

    contentDir = 'content/fr'
    disabled = false
    languageCode = 'fr-FR'
    languageDirection = 'ltr'
    languageName = 'Français'
    title = 'Olessia, votre psychothérapeute'
    weight = 1

    [languages.fr.params]
      subtitle = 'Vivez sans regrets'